name: CI

on:
  push:
    branches-ignore: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: gradle

    - name: Build
      run: ./gradlew

    - name: Test
      run: ./gradlew test

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: build/libs/*
